-- MySQL Script generated by MySQL Workbench
-- Thu Jun 17 02:59:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `Client name` VARCHAR(45) NOT NULL,
  `ListOfPersonaACC` JSON NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TariifMO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TariifMO` (
  `idTariifMO` INT NOT NULL AUTO_INCREMENT,
  `OperatorName` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(6,2) NOT NULL,
  `Bonus` DECIMAL(6,2) NULL,
  PRIMARY KEY (`idTariifMO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TariffMT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TariffMT` (
  `idTariffMT` INT NOT NULL AUTO_INCREMENT,
  `OperatorName` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(6,2) NOT NULL,
  `Bonus` DECIMAL(6,2) NULL,
  PRIMARY KEY (`idTariffMT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PersonalAcc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PersonalAcc` (
  `idPersonalAcc` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `idTariffMO` INT NULL,
  `idTariffMT` INT NULL,
  `SMSPerMonth` INT NOT NULL,
  PRIMARY KEY (`idPersonalAcc`),
  INDEX `idClient_idx` (`idClient` ASC) VISIBLE,
  INDEX `idTariffMO_idx` (`idTariffMO` ASC) VISIBLE,
  INDEX `idTariffMT_idx` (`idTariffMT` ASC) VISIBLE,
  CONSTRAINT `idClient`
    FOREIGN KEY (`idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idTariffMO`
    FOREIGN KEY (`idTariffMO`)
    REFERENCES `mydb`.`TariifMO` (`idTariifMO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idTariffMT`
    FOREIGN KEY (`idTariffMT`)
    REFERENCES `mydb`.`TariffMT` (`idTariffMT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
